services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=sql
      - MYSQL_PASSWORD=sql
      - MYSQL_DATABASE=sql
      - MYSQL_ROOT_PASSWORD=sql
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
