### Definir variáveis
@baseUrl = http://localhost:8080

### Registrar um novo usuário
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "nickname": "john",
  "email": "john.doe@yahoo.com",
  "password": "123",
  "role": "USER"
}

### Fazer login com um usuário existente
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "nickname": "john",
  "password": "123"
}